### ISSUE TITLE
Error when plugin is used for number input

### ISSUE THREAD

**Issue by indapublic** [e-hein/emulate-tab#15]
```
react-dom.development.js:4091 Uncaught DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('number') does not support selection.
    at emulateTabFromSourceToTarget (https://my.localhost:8000/build/v2.js:77055:35)
    at emulateTab (https://my.localhost:8000/build/v2.js:76974:12)
    at Object.onChange (https://my.localhost:8000/build/v2.js:6316:71)
    at onChange (https://my.localhost:8000/build/v2.js:7380:31)
    at HTMLUnknownElement.callCallback (https://my.localhost:8000/build/v2.js:122523:14)
    at Object.invokeGuardedCallbackDev (https://my.localhost:8000/build/v2.js:122572:16)
    at invokeGuardedCallback (https://my.localhost:8000/build/v2.js:122634:31)
    at invokeGuardedCallbackAndCatchFirstError (https://my.localhost:8000/build/v2.js:122648:25)
    at executeDispatch (https://my.localhost:8000/build/v2.js:126821:3)
    at processDispatchQueueItemsInOrder (https://my.localhost:8000/build/v2.js:126853:7)
rethrowCaughtError @ react-dom.development.js:4091
processDispatchQueue @ react-dom.development.js:8292
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```

**Comment by AshMcConnell** [comment]
This can be fixed by changing : -

```
if (target instanceof HTMLInputElement) {
        target.selectionStart = 0;
}
```

to 

```
if (target instanceof HTMLInputElement && target.type !== 'number') {
        target.selectionStart = 0;
}
```

**Comment by AshMcConnell** [comment]
I created a merge request here: - https://github.com/e-hein/emulate-tab/pull/18

**Comment by e-hein** [comment]
should be solved in version 1.2.1

thanks @AshMcConnell 

@indapublic could you verify that and close the issue?

**Comment by indapublic** [comment]
@e-hein Will do tomorrow. Thanks @AshMcConnell

**Comment by indapublic** [comment]
Works like a charm! Thank you @AshMcConnell  and @e-hein. Closed
